########################
### GLOBAL VARIABLES ###
########################
@baseurl = http://localhost:8080/api/v1
@adminBearerToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY5OTQzODE0MCwiZXhwIjoxNjk5NDM5NTgwfQ.sgclEeKrM5Z7mIpTNUfVDMztlNEb2GrdGG7luZ7cmiE
@userBearerToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdXN0IiwiaWF0IjoxNjk5NDM4MTQwLCJleHAiOjE2OTk0Mzk1ODB9.l1w_x9dwFAyXhztTXta0BREyOfdKcadjjaLY2SwOaH0

####################
### USER METHODS ###
####################

/// Get users
GET {{baseurl}}/users
Authorization: Bearer {{adminBearerToken}}

###

// Get details of user
GET {{baseurl}}/users/2
Authorization: Bearer {{userBearerToken}}

###

// Register new user
POST {{baseurl}}/auth/register-user
Content-Type: application/json

{
    "firstName" : "Evan",
    "lastName" : "Walker",
    "username" : "evanwalkeroo000",
    "email" : "evan@gmail.com",
    "password" : "password",
    "gender" : "MALE",
    "phoneNumber" : 98247183

}

###

// Authenticate user
POST {{baseurl}}/auth/authenticate
Content-Type: application/json

{
    "username" : "admin",
    "password" : "abcdef"
}

#####################
### EVENT METHODS ###
#####################

// Get events
GET {{baseurl}}/events
Authorization: Bearer {{adminBearerToken}}

###

// Get an event
GET {{baseurl}}/events/1
Authorization: Bearer {{adminBearerToken}}

###

// Add an event
POST {{baseurl}}/events
Content-Type: application/json
Authorization: Bearer {{adminBearerToken}}

{
    "name" : "The Genesis Event",
    "description" : "This is the origin event",
    "startDate" : "2023-09-25T21:30",
    "endDate" : "2023-09-27T19:00"
}

###

// Update an event's details (not including venue, cat and runs)
PUT {{baseurl}}/events/1
Content-Type: application/json
Authorization: Bearer {{adminBearerToken}}

{
    "name" : "The Genesys Event",
    "startDate" : "2023-09-27T19:00",
    "endDate" : "2023-09-30T21:00"
}

###

// Update an event's venue
PUT {{baseurl}}/events/3/venue/2
Authorization: Bearer {{adminBearerToken}}

###

// Add new run to event
POST {{baseurl}}/events/1/runs
Content-Type: application/json
Authorization: Bearer {{adminBearerToken}}

{
    "name" : "Special run for event 1",
    "description" : "The special run for event 1.",
    "startRunDate" : "2023-11-04T15:00",
    "endRunDate" : "2023-11-05T12:00",
    "startBidDate" : "2023-11-04T15:00",
    "endBidDate" : "2023-11-05T12:00"
}

###

// Get runs of event
GET {{baseurl}}/events/1/runs
Authorization: Bearer {{adminBearerToken}}

###

// Update run
PUT {{baseurl}}/runs/1
Content-Type: application/json
Authorization: Bearer {{adminBearerToken}}

{
    "name" : "An updated run",
    "description" : "Run for testing update run method.",
    "startRunDate" : "2023-11-04T20:00",
    "endRunDate" : "2023-11-05T20:00",
    "startBidDate" : "2024-11-04T15:00",
    "endBidDate" : "2024-11-05T12:00"
}

###

// Delete run
DELETE {{baseurl}}/runs/1
Authorization: Bearer {{adminBearerToken}}

###

// Delete an event
DELETE {{baseurl}}/events/1
Authorization: Bearer {{adminBearerToken}}



#####################
### VENUE METHODS ###
#####################

// Get venues
GET {{baseurl}}/venues
Authorization: Bearer {{adminBearerToken}}

###

// Get a venue
GET {{baseurl}}/venues/1
Authorization: Bearer {{adminBearerToken}}

###

// Add an venue
POST {{baseurl}}/venues
Content-Type: application/json
Authorization: Bearer {{adminBearerToken}}

{
    "name" : "The Genesis Stadium",
    "address" : "Genesis address"
}

###

// Update a venue
PUT {{baseurl}}/venues/1
Content-Type: application/json
Authorization: Bearer {{adminBearerToken}}

{
    "name" : "The Genesys Stadium",
    "address" : "Genesys address"
}

###

// Delete an venue
DELETE {{baseurl}}/venues/1
Authorization: Bearer {{adminBearerToken}}


######################
### TICKET METHODS ###
######################

// Get current user's tickets
GET {{baseurl}}/tickets
Authorization: Bearer {{userBearerToken}}

###

// Assign new ticket to current user
PUT {{baseurl}}/tickets/5
Authorization: Bearer {{userBearerToken}}

###

// Get the price of a user's ticket
GET {{baseurl}}/tickets/2
Authorization: Bearer {{userBearerToken}}


#######################
### BIDDING METHODS ###
#######################

# // Add new queue entry
# POST {{baseurl}}/queue-entry/1/1
# Authorization: Bearer {{userBearerToken}}


# ###

# // Start bidding
# POST {{baseurl}}/run/1/biddingstart

# ###

# // Get bidding entry
# GET {{baseurl}}/queue-entry/1/1
# Authorization: Bearer {{userBearerToken}}
