name: Deploy Application

on:
  workflow_run:
    workflows: ["Build and Push React App Docker Image","Build and Push Spring Boot Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker Images
        if: ${{ github.event.workflow_run.conclusion == 'success' &&
                 contains(github.event.workflow_run.workflow, 'Build and Push React App Docker Image') &&
                 contains(github.event.workflow_run.workflow, 'Build and Push Spring Boot Docker Image') &&
                 github.event.workflow_run.head_workflow == 'Build and Push Spring Boot Docker Image' }}
        run: |
          docker pull smallsish/seatsecure-ui-repo
          docker pull smallsish/backend-repo
          docker pull badatcoding/postgres

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f /home/ec2-user/compose.yaml up -d
        shell: bash