name: Deploy Application

on:
  workflow_run:
    workflows: ["Build and Push React App Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Stop and Remove Existing Containers, except postgres
        run: |
          docker stop $(docker ps -q | grep -v "$(docker ps -q -f name=postgres)")
          docker rm -f $(docker ps -aq | grep -v "$(docker ps -q -f name=postgres)")
          docker rmi -f $(docker images -q | grep -v "postgres")

      - name: Pull Docker Images
        run: |
          docker pull smallsish/seatsecure-ui-repo:latest
          docker pull smallsish/backend-repo:latest


      - name: Deploy with Docker Compose
        run: |
          docker-compose -f compose.yaml up -d
        shell: bash